### ISSUE TITLE
pip install does not auto-install requirements

### ISSUE THREAD

**Issue by neubig** [neulab/compare-mt#118]
For example:

    $ pip install compare_mt
    Collecting compare_mt
      Downloading https://files.pythonhosted.org/packages/e9/4c/e18ea230d656e273a1dd8a0fcea74154ebb343ea471dce7e95a6cd74ed7d/compare_mt-0.2.8.tar.gz (43kB)
         |████████████████████████████████| 51kB 2.2MB/s 
        ERROR: Command errored out with exit status 1:
         command: /home/gneubig/anaconda3/envs/python3/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-sieojamx/compare-mt/setup.py'"'"'; __file__='"'"'/tmp/pip-install-sieojamx/compare-mt/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-install-sieojamx/compare-mt/pip-egg-info
             cwd: /tmp/pip-install-sieojamx/compare-mt/
        Complete output (9 lines):
        Traceback (most recent call last):
          File "<string>", line 1, in <module>
          File "/tmp/pip-install-sieojamx/compare-mt/setup.py", line 4, in <module>
            import compare_mt
          File "/tmp/pip-install-sieojamx/compare-mt/compare_mt/__init__.py", line 5, in <module>
            import compare_mt.scorers
          File "/tmp/pip-install-sieojamx/compare-mt/compare_mt/scorers.py", line 1, in <module>
            import nltk
        ModuleNotFoundError: No module named 'nltk'
        ----------------------------------------
    ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

**Comment by neubig** [comment]
Fixed by https://github.com/neulab/compare-mt/commit/4d2fc9419df001d2e28a588a29ec614187677dcd
